services:

  postgres:
    image: postgres:15
    container_name: postgres_history
    restart: always
    environment:
      POSTGRES_USER: history_user
      POSTGRES_PASSWORD: history_pass
      POSTGRES_DB: calculator_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    image: houssitcol2019/calculator_app:latest
    container_name: spring_calculator_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: calculator_db
      POSTGRES_USER: history_user
      POSTGRES_PASSWORD: history_pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LAMBDA_ENDPOINT_URL: https://bxnbq4uy6jhisd5mlnk7273zoi0jyfyr.lambda-url.us-east-1.on.aws
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
